---
apiVersion: batch/v1
kind: Job
metadata:
  name: newrelic-kube-bench-integration
spec:
  template:
    metadata:
      labels:
        app: newrelic-kube-bench-integration
    spec:
      hostPID: true
      containers:
        - name: newrelic-kube-bench-forwarder
          image: busybox:1.28 #TODO: use proper docker image reference 
          command: ['sh', '-c', 'cat $(REPORT_FILE_DIRECTORY); printf KEY_NR=$NEW_RELIC_LICENCE_KEY'] #TODO: 
          env:
          - name: NEW_RELIC_LICENCE_KEY
            valueFrom:
              secretKeyRef:
                name: nr-api-key-secret
                key: apikey
          - name: REPORT_FILE_DIRECTORY
            value: "/report/report.json"
          volumeMounts:
          - mountPath: /report
            name: report-directory
      initContainers:
      - name: kube-bench
        image: docker.io/aquasec/kube-bench:v0.6.10
        command: ["kube-bench", "--json", "--outputfile", "$(REPORT_FILE_DIRECTORY)"]
        env:
        - name: REPORT_FILE_DIRECTORY
          value: "/report/report.json"
        volumeMounts:
          - name: report-directory
            mountPath: /report
          - name: var-lib-etcd
            mountPath: /var/lib/etcd
            readOnly: true
          - name: var-lib-kubelet
            mountPath: /var/lib/kubelet
            readOnly: true
          - name: var-lib-kube-scheduler
            mountPath: /var/lib/kube-scheduler
            readOnly: true
          - name: var-lib-kube-controller-manager
            mountPath: /var/lib/kube-controller-manager
            readOnly: true
          - name: etc-systemd
            mountPath: /etc/systemd
            readOnly: true
          - name: lib-systemd
            mountPath: /lib/systemd/
            readOnly: true
          - name: srv-kubernetes
            mountPath: /srv/kubernetes/
            readOnly: true
          - name: etc-kubernetes
            mountPath: /etc/kubernetes
            readOnly: true
            # /usr/local/mount-from-host/bin is mounted to access kubectl / kubelet, for auto-detecting the Kubernetes version.
            # You can omit this mount if you specify --version as part of the command.
          - name: usr-bin
            mountPath: /usr/local/mount-from-host/bin
            readOnly: true
          - name: etc-cni-netd
            mountPath: /etc/cni/net.d/
            readOnly: true
          - name: opt-cni-bin
            mountPath: /opt/cni/bin/
            readOnly: true
      restartPolicy: Never
      volumes:
        - name: var-lib-etcd
          hostPath:
            path: "/var/lib/etcd"
        - name: var-lib-kubelet
          hostPath:
            path: "/var/lib/kubelet"
        - name: var-lib-kube-scheduler
          hostPath:
            path: "/var/lib/kube-scheduler"
        - name: var-lib-kube-controller-manager
          hostPath:
            path: "/var/lib/kube-controller-manager"
        - name: etc-systemd
          hostPath:
            path: "/etc/systemd"
        - name: lib-systemd
          hostPath:
            path: "/lib/systemd"
        - name: srv-kubernetes
          hostPath:
            path: "/srv/kubernetes"
        - name: etc-kubernetes
          hostPath:
            path: "/etc/kubernetes"
        - name: usr-bin
          hostPath:
            path: "/usr/bin"
        - name: etc-cni-netd
          hostPath:
            path: "/etc/cni/net.d/"
        - name: opt-cni-bin
          hostPath:
            path: "/opt/cni/bin/"
        - name: report-directory
          emptyDir:
            sizeLimit: 500Mi


---
apiVersion: v1
data:
  apikey: Mzk1MjgkdmRnN0pi #TODO: use proper secret here
kind: Secret
metadata:
  name: nr-api-key-secret
type: Opaque